# =======================
# PostgreSQL (Development)
# =======================
spring.datasource.url=jdbc:postgresql://localhost:5432/smartlaundry
spring.datasource.username=laundry_admin
spring.datasource.password=@Aw35omes
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# --- JWT ---
jwt.jwtSecret=bf343c55a235c3c70b0c45b115987867784cc9e5fac8931c29003f113b7b11287dd2fa80d87c70f6adef647d3a82c72a906f7671efdf379d729425109de2782e
jwt.jwtExpiration=3600000

# =========================================
# MAIL CONFIG (Google SMTP or fallback)
# =========================================
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USER:nndungu7@gmail.com}
spring.mail.password=${MAIL_PASSWORD:opkalsemqzwkcwlf}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS_ENABLE:true}
spring.mail.default-encoding=UTF-8
spring.mail.test-connection=false
