# Bind server to all network address interfaces
server.address=0.0.0.0

# API port
server.port=8080

# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER:laundry_dmin}
spring.datasource.password=${DB_PASSWORD:@Aw35omes}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# ===============================
# JPA CONFIGURATION
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# ===============================
# SCRIPT INITIALIZATION
# ===============================
spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
spring.sql.init.continue-on-error=true

# =======================
# JWT Configuration
# =======================
jwt.secret=bf343c55a235c3c70b0c45b115987867784cc9e5fac8931c29003f113b7b11287dd2fa80d87c70f6adef647d3a82c72a906f7671efdf379d729425109de2782e
jwt.expiration=3600000

# =========================================
# MAIL CONFIG (Google SMTP or fallback)
# =========================================
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USER:nndungu7@gmail.com}
spring.mail.password=${MAIL_PASSWORD:opkalsemqzwkcwlf}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS_ENABLE:true}
spring.mail.default-encoding=UTF-8
spring.mail.test-connection=false


# Africa's Talking
africastalking.username=${AFRICASTALKING_USERNAME:sandbox}
africastalking.apiKey=${AFRICASTALKING_API_KEY:atsk_76225250fa58d373b04526b4bd3ba3cb1337504c7b4ccdc64820f19d40cfa9275f84fe67}
africastalking.senderId=${AFRICASTALKING_SENDER_ID:SmartLaundry}
africastalking.base-url=${AFRICASTALKING_BASE_URL:https://api.africastalking.com}

# --- Logging ---
logging.level.org.springframework=INFO
logging.level.ke.co.smartlaundry=DEBUG

spring.profiles.active=dev
