spring.application.name=SmartLaundry
server.port=8080

# Load optional environment variables from .env.properties (local only)
spring.config.import=optional:file:.env.properties

# Default profile (local development)
spring.profiles.active=${SPRING_PROFILES_ACTIVE:prod}

spring.main.banner-mode=off

# ===============================
# DATABASE (Render / Docker)
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.clean-disabled=true

# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:3600000}



# Logging
logging.level.root=INFO
logging.level.ke.co.smartlaundry=DEBUG
logging.file.name=logs/smartlaundry.log


