# -----------------------------
# LOCAL DEVELOPMENT DATABASE
# -----------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/smartlaundry_db}
spring.datasource.username=${DB_USER:laundry_admin}
spring.datasource.password=${DB_PASSWORD:@Aw35omes}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Flyway for local dev
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration,classpath:db
spring.flyway.clean-disabled=true

# ==============================
# JWT (Local Only)
# ==============================
jwt.secret=bf343c55a235c3c70b0c45b115987867784cc9e5fac8931c29003f113b7b11287dd2fa80d87c70f6adef647d3a82c72a906f7671efdf379d729425109de2782e
jwt.expiration=3600000

# ==============================
# EMAIL (Local Only)
# ==============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nndungu7@gmail.com
spring.mail.password=fgtvbbfqqpbbsalf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ==============================
# M-PESA SANDBOX (Local Only)
# ==============================
mpesa.env=sandbox
mpesa.base.url=https://sandbox.safaricom.co.ke
mpesa.consumerKey=gVYeSNRjC6ZG99jUfXBsHsqFuu8F1Gjqh8Tv4WBbn5N7DGc8
mpesa.consumerSecret=IGDDwaGAXA2p3jYdp5TzslgY9E0Qed0umta2D9WbscdZIBpXNFG97piuulPgzYZZ
mpesa.shortcode=174379
mpesa.passkey=bfb279f9aa9bdbcf158e97dd71a467cd2e0e6c1e2c0fdd0b18c1b1a3f6e8e5b9
mpesa.callbackUrl=https://smartlaundry-api.onrender.com/api/payments/mpesa/callback

# ==============================
# Africa's Talking (Local Only)
# ==============================
africastalking.username=SmartLaundry
africastalking.apiKey=atsk_76225250fa58d373b04526b4bd3ba3cb1337504c7b4ccdc64820f19d40cfa9275f84fe67
africastalking.senderId=SmartLaundry

# ==============================
# Google OAuth2 (Local Only)
# ==============================
google.client.id=593370389690-ndiuh3ajm99av9q85eci12ldrvuqg3v5.apps.googleusercontent.com
google.client.secret=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
google.redirect.uri=https://developers.google.com/oauthplayground

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ==============================
# TEST MODE
# ==============================
spring.test.database.replace=none